### ISSUE TITLE
no need for mqtt connection for every device

### ISSUE THREAD

**Issue by TradeFace** [TradeFace/tuyamqtt#69]
Main class can listen and route commands internally.

**Comment by emontnemery** [comment]
This is a good idea.
Are you already working on it?
If you're not I'd like to give it a try.

**Comment by TradeFace** [comment]
No go ahead. I am breaking my head over how to implement device properties currently

**Comment by TradeFace** [comment]
I'm removing the topic configuration option. To much trouble to keep it working next to gismocaster.
There probably not many users of it anyway. So, it is a waist of time compared to other usability that could be gained in the same time. Since it is now a breaking change I upped it to v2.0

**Comment by emontnemery** [comment]
Availability should be updated based on two things:
- Connection to MQTT broker
- Connection to the Tuya device

I think what you mean is that availability topic and message is fixed in home assistant, which means a unique connection to the MQTT broker for each device is needed to be able to separate availability per device.

I actually think there might be a limitation in Home Assistant here.

@koenkk Is this solved in zigbee2mqtt somehow?

**Comment by TradeFace** [comment]
I didn't really dive into it. I looped through the `will_set` for each datapoint within a device and noticed only one came unavailable in HA when I stopped the tuyagateway. When I give the datapoints the same availability topic all will come unavailable in HA (once TG stops). So, on a per device bases it can be managed (which is fine). I assume there is only one `will_set` per MQTT connection.

**Comment by Koenkk** [comment]
@emontnemery availability per device is solved by a different availability topic for each device. e.g. `zigbee2mqtt/my_device_1/availability`.

**Comment by TradeFace** [comment]
@Koenkk do you set a will for availability? And is it all handled over one mqtt connection? Or do you have a mqtt connection per device?

Groeten uit Steensel!

**Comment by Koenkk** [comment]
- Everything is handled over 1 MQTT connection
- No will is set when a separate availability for each device is used, it seems that the MQTT library we use doesn't support this (I don't know if this is supported at all by MQTT, I guess this is the reason why you want multiple connections?)

Groetjes uit Helmond 😄

**Comment by TradeFace** [comment]
Well, I want to get rid of the mqtt-connection per device, but then noticed (working on another issue) that the will seems to work on a per connection basis. You apparently manage to solve the availability stuff without setting a will, and all that over 1 connection. So I think the route to go is clear for this. 

Thanks for your input :+1:

**Comment by emontnemery** [comment]
@Koenkk , @TradeFace Do you think the following would work:
```yaml
availability:
 - topic: <zigbee2mqtt_or_tuyagateway_will_birth_topic>
   payload_available: A
   payload_unavailable: B
 - topic: <individual_device_availability_topic>
   payload_available: Y
   payload_unavailable: Y
```

The idea is to allow configuring a list of availability-settings

**Comment by TradeFace** [comment]
Is the idea that all in the list will follow the `will_birth_topic` status? I think that could work. But how would you determine which is the actual `will_birth_topic`?

**Comment by emontnemery** [comment]
the idea is that you're allowed to configure a list of availability topics:

Possible now:
```json
{"availability_topic": "available"}
```

Proposal:
```json
{["availability_topic": "available1"], ["availability_topic": "available2"]}
```

**Comment by TradeFace** [comment]
I don't think I fully understand how this should work. 

Let's say I have tuyagateway with one tuya devices connected. When the TG can't connect to the device it will publish `"offline"` to `"some_device/status"`; `"tuyagateway/status"` will not publish anything and thus keeps state `"online"`. How can HA understand what the actual state is? It now has conflicting information.  

IMO you need a way to determine hierarchy between the availability topics. Be it a specialized `availability_will_topic` that takes president over the `availability_topic`. Or the first in the list overrules the rest. Or perhaps a extra  property in the list. 

```yaml
availability:
 - topic: <individual_device_availability_topic>
   payload_available: X
   payload_unavailable: Y
 - topic: <zigbee2mqtt_or_tuyagateway_will_birth_topic>
   payload_available: A
   payload_unavailable: B
   master: true
```
